### ISSUE TITLE
TLV negotiation fails when mettle is run in a chroot environment where /dev/random is not present

### ISSUE THREAD

**Issue by jheysel-r7** [rapid7/mettle#255]
When testing the following metasploit module https://github.com/rapid7/metasploit-framework/pull/18832 @smcintyre-r7 discovered that TLV negotiation was failing because mettle was being run from an chroot'd environment where `/dev/random` and `/dev/urandom` were not present. 

Copying the two random binaries from an Ubuntu 22.04 environment into the chroot environment solved the issue and allowed the meterpreter session to be established. 

Steps to recreate the issue are as follows and come from the following [write up](https://www.rapid7.com/blog/post/2024/02/13/cve-2023-47218-qnap-qts-and-quts-hero-unauthenticated-command-injection-fixed/) by @sfewer-r7:
Live download link for the firmware: [TS-X64_20230926-5.1.2.2533.zip](https://download.qnap.com/Storage/TS-X64/TS-X64_20230926-5.1.2.2533.zip)

Decrypting the firmware:
```
user@dev:~/qnap/$ ls
TS-X64_20230926-5.1.2.2533.zip
# Unzip the firmware.
user@dev:~/qnap/$ unzip TS-X64_20230926-5.1.2.2533.zip 
Archive:  TS-X64_20230926-5.1.2.2533.zip
  inflating: TS-X64_20230926-5.1.2.2533.img  
user@dev:~/qnap/$ ls
TS-X64_20230926-5.1.2.2533.img  TS-X64_20230926-5.1.2.2533.zip
# Decrypt the firmware using the tool qnap-qts-fw-cryptor.
user@dev:~/qnap/$ python3 qnap-qts-fw-cryptor.py d QNAPNASVERSION5 TS-X64_20230926-5.1.2.2533.img TS-X64_20230926-5.1.2.2533.tgz
Signature check OK, model TS-X64, version 5.1.2
Encrypted 1048576 of all 220239236 bytes
[99% left]
[99% left]
[99% left]
...snip
[02% left]
[00% left]
[00% left]
user@dev:~/qnap/$ ls
qnap-qts-fw-cryptor.py  TS-X64_20230926-5.1.2.2533.img  TS-X64_20230926-5.1.2.2533.tgz  TS-X64_20230926-5.1.2.2533.zip
# Recreate the root file system.
user@dev:~/qnap/$ mkdir firmware
user@dev:~/qnap/$ tar -xvzf TS-X64_20230926-5.1.2.2533.tgz -C ./firmware/
user@dev:~/qnap/$ binwalk -e firmware/initrd.boot
user@dev:~/qnap/$ binwalk -e firmware/_initrd.boot.extracted/0
user@dev:~/qnap/$ binwalk -e firmware/rootfs2.bz
user@dev:~/qnap/$ binwalk -e firmware/_rootfs2.bz.extracted/0
user@dev:~/qnap/$ mv firmware/_rootfs2.bz.extracted/_0.extracted/* firmware/_initrd.boot.extracted/_0.extracted/cpio-root/
```
Running the firmware:
```
user@dev:~/qnap/$ cd firmware/_initrd.boot.extracted/_0.extracted/cpio-root/
# Copy the qemu-x86_64-static binary into the root file system folder.
user@dev:~/qnap/firmware/_initrd.boot.extracted/_0.extracted/cpio-root$ cp $(which qemu-x86_64-static) .
# Run _thttpd_ via QEMU.
user@dev:~/qnap/firmware/_initrd.boot.extracted/_0.extracted/cpio-root$ sudo chroot . ./qemu-x86_64-static usr/local/sbin/_thttpd_ -p 8080  -nor -nos -u admin -d /home/httpd -c '**.*' -h 0.0.0.0 -i /var/lock/._thttpd_.pid
# Verify the HTTP server is running.
user@dev:~/qnap/firmware/_initrd.boot.extracted/_0.extracted/cpio-root$ sudo netstat -lnp | grep 8080
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1195417/./qemu-x86_ 
# Drop to a shell via QEMU...
user@dev:~/qnap/firmware/_initrd.boot.extracted/_0.extracted/cpio-root$ sudo chroot . /bin/sh
# Enable the component quick.cgi
sh-3.2# chmod +x /home/httpd/cgi-bin/quick/quick.cgi
# Fix a linker issue with QEMU.
sh-3.2# rm /lib/libnl-3.so.200
sh-3.2# ln -s /lib/libnl-3.so.200.24.0 /lib/libnl-3.so.200
# This folder will be present in a NAS device containing a hard drive.
sh-3.2# mkdir /mnt/HDA_ROOT
```

**Comment by sempervictus** [comment]
Oof - probably a good idea to carry a primitive RNG for this case as this likely applies to properly locked down systemd services too.

**Comment by zeroSteiner** [comment]
Yeah mbedtls has two compile flags that can enable less secure sources of entropy which are probably better than nothing. https://mbed-tls.readthedocs.io/en/latest/kb/how-to/add-entropy-sources-to-entropy-pool/#default-entropy-sources

Enabling those is one option we're considering.

**Comment by adfoster-r7** [comment]
I think we'd be able to send an error code back that the encryption mechanism has failed after this request:

```
SEND: #<Rex::Post::Meterpreter::Packet type=Request         tlvs=[
  #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=16 command=core_negotiate_tlv_encryption>
  #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="56933536539681039894289159240630">
  #<Rex::Post::Meterpreter::Tlv type=RSA_PUB_KEY     meta=RAW        value="0\x82\x01\"0\r\x06\t*\x86H\x86\xF7\r\x01\x01\x01\ ...">
]>

RECV: <PacketResponse indicating failure that we can handle gracefully>
```

We could use that to generate a warning to the user, and let them opt into less secure comms if it makes sense for their usecase/scenario. They could tweak datastore options and have the second encryption attempt happen with less secure entropy - if there's a runtime option for that.

**Comment by sempervictus** [comment]
> I think we'd be able to send an error code back that the encryption mechanism has failed after this request:
> 
> ```
> SEND: #<Rex::Post::Meterpreter::Packet type=Request         tlvs=[
>   #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=16 command=core_negotiate_tlv_encryption>
>   #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="56933536539681039894289159240630">
>   #<Rex::Post::Meterpreter::Tlv type=RSA_PUB_KEY     meta=RAW        value="0\x82\x01\"0\r\x06\t*\x86H\x86\xF7\r\x01\x01\x01\ ...">
> ]>
> 
> RECV: <PacketResponse indicating failure that we can handle gracefully>
> ```
> 
> We could use that to generate a warning to the user, and let them opt into less secure comms if it makes sense for their usecase/scenario. They could tweak datastore options and have the second encryption attempt happen with less secure entropy - if there's a runtime option for that.
> 
> Maybe for the next steps we could just print out an error message to the user for now what went wrong, and point them to a github issue or something to interact with?

This is the stuff of which downgrade attacks are made. One of my eternal crusades in this space is securing _our_ comms (hence all the horrors re ssl shells) so i'm pretty loathe to give an ALG through which we pass the ability to intermediate and downgrade us by error code. Personally much more a fan of including a software RNG of our own or getting hacker-is w/ entropy sources (hell, hash a log stream's last few lines for some bits along with a high precision timer - we can figure this out).

**Comment by zeroSteiner** [comment]
I think @adfoster-r7's suggestion intended to make it known to the user and require them to opt into using an alternative and less secure entropy source, ideally `MBEDTLS_TIMING_C` and `MBEDTLS_HAVEGE_C` if possible. @sempervictus are you advocating for using those entropy source just automatically because making it an option could open users to a downgrade attack where those sources would be used when a more secure one is available? That kinda makes sense because the additional logic could be an attack surface. We could implement it as a flag in the negotiation that simply enables weaker entropy sources but have Meterpreter (mettle in this case) continue to prefer strong ones, so it would just check for access to a strong one twice.

Negotation would go something like
```
MSF -> negotiate(enable_weak=False) -> Mettle
   * mettle tries secure source, then fails*
    <- ERROR_NO_ENTROPY <-
    -> negotiate(enable_weak=True) ->
    * mettle tries secure source, then tries weak source, then succeeds*
    <- ERROR_SUCCESS <-
```

In this case the downgrade would require that the target require a weak source of entropy to begin with, otherwise the flag would be ignored since we'd still try the secure source.

Another, entirely different option we had considered was falling back to the weaker sources of entropy automatically, again we'd try to use the ones mbedtls provides. When it was necessary to fall back to a weaker entropy source and thus the key may not be truly random, a TLV would be sent back to MSF. MSF on receiving said TLV would present a warning to the user and halt the session bootstrapping process so that stdapi is not loaded and auto-run scripts are not run. This would have the advantage that the payload would only need to be executed once and the user could decide whether or not to interact with it once they've been warned. This sounds very similar to what you're suggesting with the additional warning sent back to MSF that would then be processed as described.

**Comment by sempervictus** [comment]
I like the latter option: fallback to a less safe but still "our" source without additional comms in cleartext and then send back the notice to the framework telling it weve done so and giving the user a choice re whether to continue. I don't imagine a simple RNG would bloat us too much...

**Comment by dledda-r7** [comment]
I investigated the issue reading the mbedtls code, The usage of `MBEDTLS_TIMING_C` and `MBEDTLS_HAVEGE_C` may not be the correct approach due to the following reasons:
1. As stated inside the mbedtls documentation regarding the entropy, "The entropy module refuses to deliver entropy unless it has at least one strong source." and both `MBEDTLS_TIMING_C` and `MBEDTLS_HAVEGE_C` are considered weak algorithm with the result that even enabling them the entropy generation will most likely fail due to the lack of a strong algorithm.
2. Without changing the mbedtls code, it will not be possible to determinate when the "weak" entropy is used. Internally, mbedtls, during the entropy init adds the source in a "sources" struct array with the different callbacks to generate the entropy, then when a seed is requested, it goes through the array and execute all the entropy generation callbacks, so there is no way to perform a seed generation with a flag `weak=False` or `weak=True` without altering the mbedtls code.
3. The final issue is that both `MBEDTLS_TIMING_C` and `MBEDTLS_HAVEGE_C` are deprecated in mbedtls 3.x and when we will update the library we will have to take care of it.

My proposal is, as @sempervictus suggested, to include a PRNG algorithm inside mettle, that may be mbedtls compatible and do the following steps:

1. try to setup the encryption key with strong entropy
2. fail, notify the user (not sure how this works in meterpreter protocol)
3. proceeds to add the new source of entropy using the mbedtls api, flagging the PRNG as strong_algorithm (otherwise mbedtls will not work)
4. run the entropy generation
5. negotiate the key with the c2

I suggest a common PRNG algorithm called Marsenne Twister, there is a free C implementation we can include: https://github.com/ESultanik/mtwister
